### Broadcasting Rule
    *Dimensions Should be equal
    *There should be 1 present  in any one array.{ like (1x3)(3x1)}

In [12]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [13]:
b = np.array([[1],[2],[3]])
print(b)

[[1]
 [2]
 [3]]


In [14]:
print(a+b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [16]:
x = np.array([[1,2,3],[4,5,6]])
x.shape

(2, 3)

In [18]:
y = np.array([[5],[6]])
y.shape

(2, 1)

In [19]:
x+y

array([[ 6,  7,  8],
       [10, 11, 12]])

In [20]:
val1 = np.array([[1,2,3],[4,5,6]])
val1.shape

(2, 3)

In [21]:
val2 = np.array([[1,2,3,4],[4,5,6,7]])
val2.shape

(2, 4)

In [22]:
val1 + val2

ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 