In [1]:
import numpy as np

## Creating ndarrays

In [2]:
data1 = [5,6,7.8,9.5]
arr1 = np.array(data1)

In [3]:
arr1

array([5. , 6. , 7.8, 9.5])

In [4]:
data2 = [[1,2,3,4],[5,6,7,8,]]
arr2 = np.array(data2)

In [5]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr2.ndim

2

In [7]:
arr2.shape

(2, 4)

In [8]:
arr2.size

8

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int32')

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
#3D array (x,y,z)
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])

In [17]:
arr1.dtype

dtype('int32')

In [18]:
arr2.dtype

dtype('int32')

In [22]:
arr2 = arr2.astype('float64')

In [23]:
arr2.dtype

dtype('float64')

## Simple Airthmatic Operations

In [28]:
arr = np.array([[1,2,3,4] , [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr * arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [30]:
arr + arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [31]:
arr - arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
arr / arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
1 / arr

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [34]:
arr ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [35]:
arr2 = np.array([[0,4,9],[5,7,8]])
arr2

array([[0, 4, 9],
       [5, 7, 8]])

In [36]:
arr2 > arr

ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 